version: "3"
services:
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    volumes:
      - ./backend:/app/backend
      - ./dev_seed_data:/app/dev_seed_data
      - ./signer:/app/signer
      - /tmp/contentstore
      - typescript-dtos:/typescript-dtos
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      STORE_TYPE: local
      # If using GCP or S3...
      # STORE_BUCKET: 
      # If using S3...
      # STORE_REGION: 
      APP_CSRF_AUTH_KEY: ""
      APP_SESSION_STORE_KEY: ""
      APP_PORT: 3000
      APP_FRONTEND_INDEX_URL: "http://localhost:8080"
      APP_BACKEND_URL: "http://localhost:8080/web"
      APP_SUCCESS_REDIRECT_URL: "http://localhost:8080"
      APP_FAILURE_REDIRECT_URL_PREFIX: "http://localhost:8080"
      # APP_FLAGS are comma separated strings
      APP_FLAGS: "welcome-message"
      DB_URI: dev-user:dev-user-password@tcp(db:3306)/dev-db
      APP_USE_LAMBDA_RIE: "true"

      ENABLE_EVIDENCE_EXPORT: "false"

      # Common Value for all emailers
      EMAIL_FROM_ADDRESS: AShirt

      # For normal testing (writes plaintext emails to stdout)
      EMAIL_TYPE: stdout

      # For SMTP (specifically, gmail) setup
      # EMAIL_TYPE: smtp
      # EMAIL_SMTP_AUTH_TYPE: login
      # EMAIL_HOST: smtp.gmail.com:587
      # EMAIL_USER_NAME: "actual-email-account+forAshirtTesting@gmail.com"
      # EMAIL_PASSWORD: "totally-secret-password"
      
      AUTH_SERVICES: ashirt
      # AUTH_SERVICES: ashirt,google
      AUTH_SERVICES_ALLOW_REGISTRATION: ashirt
      # AUTH_WEBAUTHN_NAME: webauthn
      # AUTH_WEBAUTHN_DISPLAY_NAME: ashirt

      # Google oidc
      AUTH_GOOGLE_TYPE: oidc
      AUTH_GOOGLE_NAME: google
      AUTH_GOOGLE_FRIENDLY_NAME: Google OIDC
      AUTH_GOOGLE_PROVIDER_URL: https://accounts.google.com
      AUTH_GOOGLE_CLIENT_ID: 
      AUTH_GOOGLE_CLIENT_SECRET: 
      AUTH_GOOGLE_SCOPES: email
      AUTH_GOOGLE_DISABLE_REGISTRATION: "false"

      # Deprecated okta login
      # AUTH_OKTA_CLIENT_ID:
      # AUTH_OKTA_CLIENT_SECRET:
      # AUTH_OKTA_ISSUER: 
      # AUTH_OKTA_BACKEND_URL: "http://localhost:8080/web"
      # AUTH_OKTA_SUCCESS_REDIRECT_URL: "http://localhost:8080"
      # AUTH_OKTA_FAILURE_REDIRECT_URL_PREFIX: "http://localhost:8080"
      # AUTH_OKTA_PROFILE_TO_SHORTNAME_FIELD: preferred_username

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - typescript-dtos:/app/src/services/data_sources/dtos
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - WEB_BACKEND_ORIGIN=http://backend:3000

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=dev-db
      - MYSQL_ROOT_PASSWORD=dev-root-password
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-user-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  demo:
    image: ashirt/tesseract-lambda-python:latest
    ports:
      - 3001:3001
    restart: on-failure
    environment:
      PORT: 3001
      ENABLE_DEV: "true"
      ASHIRT_BACKEND_URL: http://backend:3000
      ASHIRT_ACCESS_KEY: gR6nVtaQmp2SvzIqLUWdedDk
      ASHIRT_SECRET_KEY: WvtvxFaJS0mPs82nCzqamI+bOGXpq7EIQhg4UD8nxS5448XG9N0gNAceJGBLPdCA3kAzC4MdUSHnKCJ/lZD++A==

volumes:
  typescript-dtos:
